version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./app:/usr/src/app
    ports:
        - 3000:3000
    command: sh -c "npm start"
    stdin_open: true
    environment:
        - NODE_ENV=production
